name: Build Kernel RM6785

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout kernel source
      uses: actions/checkout@v3

    - name: Clone aarch64 toolchain
      run: |
        git clone --depth=1 https://github.com/arter97/arm64-gcc.git gcc
        echo "$(pwd)/gcc/bin" >> $GITHUB_PATH

    - name: Setup environment
      run: |
        sudo apt update
        sudo apt install -y bc bison flex libssl-dev make \
          libc6-dev libncurses5-dev cpio zip curl

    - name: Set environment variables
      run: |
        echo "ARCH=arm64" >> $GITHUB_ENV
        echo "CROSS_COMPILE=$(pwd)/gcc/bin/aarch64-elf-" >> $GITHUB_ENV
        echo "KERNEL_OUT=out" >> $GITHUB_ENV

    - name: Make defconfig
      run: |
        make O=$KERNEL_OUT rm6785_defconfig

    - name: Build Kernel
      run: |
        make -j$(nproc) O=$KERNEL_OUT

    - name: Clone AnyKernel3
      run: |
        git clone https://github.com/osm0sis/AnyKernel3.git

    - name: Copy kernel to AnyKernel3
      run: |
        cp $KERNEL_OUT/arch/arm64/boot/Image.gz-dtb AnyKernel3/Image.gz-dtb

    - name: Zip AnyKernel3
      run: |
        cd AnyKernel3
        zip -r9 ../flashable-kernel.zip ./*

    - name: Upload flashable zip
      uses: actions/upload-artifact@v3
      with:
        name: Flashable-Kernel-Zip
        path: flashable-kernel.zip
