name: Build Kernel RM6785

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y bc bison flex libssl-dev make \
          libc6-dev libncurses5-dev gcc clang python3 unzip git cpio curl

      - name: Clone kernel source
        run: |
          git clone --depth=1 https://github.com/realme-mt6785-devs/android_kernel_realme_mt6785 kernel
          cd kernel

      - name: Build dummy
        run: echo "Kernel build simulation complete"

      - name: Upload dummy artifact
        uses: actions/upload-artifact@v3.1.3
        with:
          name: test-output
          path: kernel/README.md
